name: flutter_mobile_application
description: Flutter mobile application boiler plate
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  json_annotation: ^3.1.0
  connectivity: ^2.0.1
  flutter_secure_storage: ^3.3.5
  rxdart: ^0.24.1
  bloc: ^6.1.0
  flutter_bloc: ^6.0.6
  meta: ^1.2.3
  equatable: ^1.2.5
  intl_utils: ^1.9.0
  flushbar: ^1.10.4
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  path_provider: ^1.6.24
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
flutter_intl:
  enabled: true
  class_name: Content
  main_locale: en
